name: dagger

on:
  push:
    branches: [main]

jobs:
  runllm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          verb: functions
      - uses: dagger/dagger-for-github@8.0.0
        with:
          verb: call
          args: 'go-program --assignment "write me a curl clone to a main.go ensure workdir points there" file --path "./main.go" contents'   
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
